_archiv/Template_app_v001/models.py
from datetime import datetime
from pytz import timezone
from app import db


def get_current_time():
    return datetime.now(tz=timezone("Europe/Zurich")).replace(second=0, microsecond=0)

_archiv/Template_app_v001/__init__.py
from flask import Blueprint
from app.logger_manager import AppLogger

logger_name = "APP-Template_app_v001"

blueprint = Blueprint(
    "Template_app_v001",
    __name__,
    url_prefix="/Template_app_v001",
    template_folder="templates",
    static_folder="static",
    static_url_path="/Template_app_v001_static",
)

app_logger = AppLogger(logger_name)
app_logger.info("Starte App-Template_app_v001 initiierung")

_archiv/Template_app_v001/routes.py
from flask import render_template, current_app as app, request, jsonify
from flask_login import current_user
from . import (
    api_routes,
    blueprint,
    app_logger,
    admin_routes,
    admin_api_routes,
    socketio_events,
    tasks,
)
from app.config import Config
from app.decorators import admin_required, enabled_required
from .app_config import AppConfig


config = Config()
app_config = AppConfig()
app_logger.info(f"Starte App-{app_config.app_name} Route Initialization")
print(f"App-{app_config.app_name} Version 0.0.0")


def is_ajax_request():
    """
    Prüft ob der Request von fetch/JavaScript kommt
    """
    return request.headers.get("X-Requested-With") == "XMLHttpRequest"


@blueprint.route("/", methods=["GET"])
@blueprint.route("/Template_app_v001_index", methods=["GET"])
@enabled_required
def Template_app_v001_index():
    return render_template(
        "Template_app_v001.html",
        user=current_user,
        config=config,
        content="dashboard",
        app_config=app_config,
    )


@blueprint.route("/dashboard", methods=["GET"])
@enabled_required
def dashboard():
    # Bei AJAX: Nur Content
    if is_ajax_request():
        return render_template(
            "content/Template_app_v001_dashboard.html",
            user=current_user,
            config=config,
            app_config=app_config,
        )

    # Normal: Komplette Seite
    return render_template(
        "Template_app_v001.html",
        user=current_user,
        config=config,
        content="dashboard",
        app_config=app_config,
    )


@blueprint.route("/page_01", methods=["GET"])
@enabled_required
def page_01():
    if is_ajax_request():
        return render_template(
            "content/Template_app_v001_page_01.html",
            user=current_user,
            config=config,
            app_config=app_config,
        )

    return render_template(
        "Template_app_v001.html",
        user=current_user,
        config=config,
        content="page_01",
        app_config=app_config,
    )


@blueprint.route("/page_02", methods=["GET"])
@enabled_required
def page_02():
    if is_ajax_request():
        return render_template(
            "content/Template_app_v001_page_02.html",
            user=current_user,
            config=config,
            app_config=app_config,
        )

    return render_template(
        "Template_app_v001.html",
        user=current_user,
        config=config,
        content="page_02",
        app_config=app_config,
    )


@blueprint.route("/page_03", methods=["GET"])
@enabled_required
def page_03():
    if is_ajax_request():
        return render_template(
            "content/Template_app_v001_page_03.html",
            user=current_user,
            config=config,
            app_config=app_config,
        )

    return render_template(
        "Template_app_v001.html",
        user=current_user,
        config=config,
        content="page_03",
        app_config=app_config,
    )


app_logger.info(f"Ende App-{app_config.app_name} Route Initialization")

_archiv/Template_app_v001/scheduler_jobs/__init__.py
from . import app_keep_alive_log

# Liste aller verfügbaren Jobs
__all__ = ["app_keep_alive_log"]

_archiv/Template_app_v001/templates/layouts/email_app_layouts/Template_app_v000_email_app_base.html
{% extends "layouts/websites/base.html" %} {% block app_styles %} {% endblock %}
{%block content %} {% endblock %}

_archiv/Template_app_v001/templates/layouts/web_app_layouts/Template_app_v001_app_settings_sidbar.html
<div class="navigation-admin" id="navigation-admin">
  <ul>
    <div class="upper_items">
      <li class="list active admin-list">
        <a
          href="{{ url_for('Template_app_v001.app_info') }}"
          class="nav-link-admin"
          data-page="app_info"
        >
          <span class="icon">
            <i class="bi bi-info-circle-fill"></i>
          </span>
          <div class="list_element">App Info</div>
        </a>
      </li>
      <li class="list admin-list">
        <a
          href="{{ url_for('Template_app_v001.app_settings_config') }}"
          class="nav-link-admin"
          data-page="config"
        >
          <span class="icon">
            <i class="sidebar-icon bi bi-sliders"></i>
          </span>
          <div class="list_element">App Konfiguration</div>
        </a>
      </li>
      <li class="list">
        <a
          href="{{ url_for('Template_app_v001.app_settings_sockets') }}"
          class="nav-link-admin"
          data-page="sockets"
        >
          <span class="icon">
            <i class="bi bi-plug-fill"></i>
          </span>
          <div class="list_element">Sockets</div>
        </a>
      </li>
      <li class="list">
        <a
          href="{{ url_for('Template_app_v001.app_settings_tasks') }}"
          class="nav-link-admin"
          data-page="tasks"
        >
          <span class="icon">
            <i class="bi bi-list-task"></i>
          </span>
          <div class="list_element">Task</div>
        </a>
      </li>
      <li class="list">
        <a
          href="{{ url_for('Template_app_v001.app_settings_logs') }}"
          class="nav-link-admin"
          data-page="logs"
        >
          <span class="icon">
            <i class="bi bi-file-text-fill"></i>
          </span>
          <div class="list_element">Logs</div>
        </a>
      </li>
      <li class="list">
        <a
          href="{{ url_for('Template_app_v001.app_settings_backup_and_restore') }}"
          class="nav-link-admin"
          data-page="backup_and_restore"
        >
          <span class="icon">
            <i class="bi bi-cloud-download"></i>
          </span>
          <div class="list_element">Backup & Restore</div>
        </a>
      </li>
    </div>
  </ul>
</div>

_archiv/Template_app_v001/templates/layouts/web_app_layouts/Template_app_v001_sidebar_vertical.html
<div class="navigation" id="navigation">
  <div class="sidbear_header">
    <button class="hamburger-menu" id="hamburgerMenu">
      <i class="bi bi-list"></i>
    </button>
    <div class="sidebar_title">Template_app_v001</div>
  </div>
  <ul>
    <div class="upper_items">
      <li class="list active">
        <a
          href="{{ url_for('Template_app_v001.dashboard') }}"
          class="nav-link"
          data-page="dashboard"
        >
          <span class="icon">
            <i class="sidebar-icon bi bi-house-door-fill"></i>
          </span>
          <div class="list_element">Dashboard</div>
        </a>
      </li>
      <li class="list">
        <a
          href="{{ url_for('Template_app_v001.page_01') }}"
          class="nav-link"
          data-page="Page_01"
        >
          <span class="icon">
            <i class="bi bi-cash-coin"></i>
          </span>
          <div class="list_element">Seite 01</div>
        </a>
      </li>
      <li class="list">
        <a
          href="{{ url_for('Template_app_v001.page_02') }}"
          class="nav-link"
          data-page="Page_02"
        >
          <span class="icon">
            <i class="bi bi-controller"></i>
          </span>
          <div class="list_element">Seite 02</div>
        </a>
      </li>
      <li class="list">
        <a
          href="{{ url_for('Template_app_v001.page_03') }}"
          class="nav-link"
          data-page="Page_03"
        >
          <span class="icon">
            <i class="bi bi-controller"></i>
          </span>
          <div class="list_element">Seite 03</div>
        </a>
      </li>
    </div>
    <div class="lower_items">
      <li class="list">
        <a href="{{ url_for('myapp.home') }}">
          <span class="icon">
            <i class="sidebar-icon bi bi-grid-3x3-gap-fill"></i>
          </span>
          <div class="list_element">Zurück zu Apps</div>
        </a>
      </li>

      {% if current_user|has_admin_rights %}
      <li class="list">
        <a
          href="{{ url_for('Template_app_v001.app_settings') }}"
          class="nav-link"
          data-page="app_settings"
        >
          <span class="icon">
            <i class="sidebar-icon bi bi-gear-fill"></i>
          </span>
          <div class="list_element">Admin</div>
        </a>
      </li>
      {% endif %}
    </div>
  </ul>
</div>

_archiv/Template_app_v001/templates/layouts/web_app_layouts/Template_app_v001_web_app_base.html
{% extends "layouts/websites/base.html" %} {% block window_title_and_icon %}
<title>{{app_config.app_name}}</title>
<link
  rel="icon"
  type="image/png"
  href="{{ url_for('Template_app_v001.static', filename='img/icon.png') }}"
/>
<!-- Alternativ für verschiedene Größen: -->
<link
  rel="icon"
  type="image/png"
  sizes="32x32"
  href="{{ url_for('Template_app_v001.static', filename='img/icon.png') }}"
/>
<link
  rel="icon"
  type="image/png"
  sizes="16x16"
  href="{{ url_for('Template_app_v001.static', filename='img/icon.png') }}"
/>
<link
  rel="apple-touch-icon"
  href="{{ url_for('Template_app_v001.static', filename='img/icon.png') }}"
/>
{% endblock %} {% block head %}
<!-- Bootstrap Icons -->
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"
/>
{% endblock %} {% block app_styles %}
<link
  rel="stylesheet"
  href="{{ url_for('Template_app_v001.static', filename='css/Template_app_v001.css') }}"
/>
<link
  rel="stylesheet"
  href="{{ url_for('Template_app_v001.static', filename='css/Template_app_v001_admin.css') }}"
/>
<link
  rel="stylesheet"
  href="{{ url_for('Template_app_v001.static', filename='css/Template_app_v001_VerticalSidbar.css') }}"
/>
{% endblock %} {% block navigation %}
<!-- Entferne Standard Navigation -->
{% endblock %} {% block footer %}
<!-- Entferne Footer -->
{% endblock %} {%block content %}
<!-- Main Content Area -->
<div class="main-content">
  <!-- Sidebar -->
  {% include "layouts/web_app_layouts/Template_app_v001_sidebar_vertical.html"
  %}

  <!-- App Content -->
  <div class="app-content">
    {% block main_content %}
    <!-- Hier kommt der spezifische App-Content rein -->
    {% endblock %}
  </div>
</div>

{% endblock %} {% block javascripts %}

<!-- Hier findest du die Seiten -->
<script>
  // Hier sind die verschiedene Seiten dokumentiert
  const url_index =
    "{{ url_for('Template_app_v001.Template_app_v001_index') }}";
  const url_app_settings = "{{ url_for('Template_app_v001.app_settings') }}";
  const url_app_tasks = "{{ url_for('Template_app_v001.app_settings_tasks') }}";

  const url_api_get_tasks = "{{ url_for('Template_app_v001.api_get_tasks') }}";
  const url_api_pause_task =
    "{{ url_for('Template_app_v001.api_pause_task', task_id='TASK_ID') }}".replace(
      "TASK_ID",
      ""
    );
  const url_api_resume_task =
    "{{ url_for('Template_app_v001.api_resume_task', task_id='TASK_ID') }}".replace(
      "TASK_ID",
      ""
    );
  const url_api_run_task =
    "{{ url_for('Template_app_v001.api_run_task', task_id='TASK_ID') }}".replace(
      "TASK_ID",
      ""
    );
  const url_api_task_info =
    "{{ url_for('Template_app_v001.api_task_info', task_id='TASK_ID') }}".replace(
      "TASK_ID",
      ""
    );

  // Socketio URLS
  const url_api_get_sockets =
    "{{ url_for('Template_app_v001.api_get_sockets') }}";
  const url_api_disconnect_socket =
    "{{ url_for('Template_app_v001.api_disconnect_socket', sid='[_SID_]') }}";
  const url_api_disconnect_all_sockets =
    "{{ url_for('Template_app_v001.api_disconnect_all_sockets') }}";

  //
</script>

<!-- Socket.IO -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.2/socket.io.js"></script>
<script src="{{ url_for('Template_app_v001.static', filename='js/Template_app_v001_socketio.js') }}"></script>
<script src="{{ url_for('Template_app_v001.static', filename='js/Template_app_v001_admin_sockets.js') }}"></script>

<script src="{{ url_for('Template_app_v001.static', filename='js/Template_app_v001.js') }}"></script>
<script src="{{ url_for('Template_app_v001.static', filename='js/Template_app_v001_sidebar_vertical.js') }}"></script>

{% endblock %}